'use client';

import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import api from '../../utils/api';
import { AlertTriangle, ArrowRight, BookOpenCheck, Bot, Building2, Check, ClipboardCopy, FilePenLine, GraduationCap, Languages, Loader2, MessageCircle, Send, ShieldCheck, Sparkles, WandSparkles } from 'lucide-react';

type ToolId = 'chat' | 'admin' | 'quiz' | 'comments' | 'translate' | 'risk';
type Message = { role: 'assistant' | 'user'; text: string };
const tools = [
  { id: 'chat' as ToolId, title: 'Ask the assistant', subtitle: 'Somali & English', icon: MessageCircle },
  { id: 'admin' as ToolId, title: 'Admin helper', subtitle: 'Plans, reports & messages', icon: Building2 },
  { id: 'quiz' as ToolId, title: 'Generate a quiz', subtitle: 'From notes or PDF', icon: BookOpenCheck },
  { id: 'comments' as ToolId, title: 'Report-card comments', subtitle: 'Specific and constructive', icon: FilePenLine },
  { id: 'translate' as ToolId, title: 'Translate announcement', subtitle: 'Somali ⇄ English', icon: Languages },
  { id: 'risk' as ToolId, title: 'Early-risk signals', subtitle: 'Attendance + grades', icon: AlertTriangle },
];
function reply(input: string) {
  const q = input.toLowerCase(); const so = /\b(maxay|sidee|waa|maxaa|iga|cashar|xisaab|barasho)\b/.test(q);
  if (/photosynthesis/.test(q)) return so ? 'Photosynthesis waa habka dhirtu iftiinka qorraxda, biyaha, iyo CO₂ ugu beddesho cunto iyo oksijiin.' : 'Photosynthesis is how plants use sunlight, water, and carbon dioxide to make glucose and oxygen.';
  if (/fraction|jajab/.test(q)) return so ? 'Jajabku waa qayb ka mid ah wax dhan. 3/4 waxay ka dhigan tahay 3 qaybood oo ka mid ah 4 qaybood oo isle’eg.' : 'A fraction is part of a whole. In 3/4, you have 3 of 4 equal parts.';
  if (/study|revision|barasho/.test(q)) return so ? 'Baro hal mowduuc 25 daqiiqo, naso 5 daqiiqo, kadibna samee 5 su’aalood oo is-imtixaan ah.' : 'Study one topic for 25 minutes, rest for 5, then answer five recall questions without notes.';
  return so ? 'Waxaan kaa caawin karaa sharaxaadda casharrada, qorshaha waxbarashada, su’aalaha tababarka, iyo turjumaadda.' : 'I can explain lessons, build a study plan, create practice questions, or translate Somali and English.';
}
function Card({ children, className = '' }: { children: React.ReactNode; className?: string }) { return <section className={`rounded-3xl border border-slate-200 bg-white shadow-sm dark:border-slate-700 dark:bg-slate-900 ${className}`}>{children}</section>; }

export default function AIAssistantPage() {
  const [active, setActive] = useState<ToolId>('chat');
  const [messages, setMessages] = useState<Message[]>([{ role: 'assistant', text: 'Salaan! Hi! Ask me a school question in Somali or English.' }]);
  const [prompt, setPrompt] = useState(''); const [name, setName] = useState('Ayaan'); const [level, setLevel] = useState('good');
  const [strength, setStrength] = useState('participates actively in class discussions'); const [focus, setFocus] = useState('checking written work carefully');
  const [announcement, setAnnouncement] = useState('Dear parents, the school will be closed tomorrow. Thank you.'); const [translated, setTranslated] = useState('');
  const [generatedComment, setGeneratedComment] = useState(''); const [busy, setBusy] = useState<ToolId | null>(null); const [notice, setNotice] = useState('');
  const [adminRequest, setAdminRequest] = useState('Ii diyaari ogeysiis waalidiinta oo ku saabsan kulanka school-ka.'); const [adminDraft, setAdminDraft] = useState('');
  const [risks, setRisks] = useState<any[]>([]); const [riskLoading, setRiskLoading] = useState(false); const [role, setRole] = useState('student');
  useEffect(() => { try { setRole(JSON.parse(localStorage.getItem('user') || '{}').role || 'student'); } catch {} }, []);
  useEffect(() => { if (active !== 'risk' || role !== 'school-admin' || risks.length) return; setRiskLoading(true); api.get('/analytics/advanced').then(r => setRisks(r.data.data.studentsAtRisk || [])).catch(() => setRisks([])).finally(() => setRiskLoading(false)); }, [active, role, risks.length]);
  const comment = useMemo(() => `${name || 'This student'} ${level === 'excellent' ? 'has made excellent progress' : level === 'good' ? 'is making steady progress' : 'is beginning to make progress'} and ${strength}. Next term, ${name || 'they'} should focus on ${focus}. Keep up the effort!`, [name, level, strength, focus]);
  const generate = async (mode: 'chat' | 'admin' | 'translate' | 'comment', input: string, context?: Record<string, string>) => {
    const response = await api.post('/ai-assistant/generate', { mode, input, context });
    setNotice(response.data.data.source === 'ai' ? '' : 'AI service is not configured; a built-in safe suggestion was used.');
    return response.data.data.text as string;
  };
  const send = async () => { const text = prompt.trim(); if (!text || busy) return; setPrompt(''); setMessages(m => [...m, { role: 'user', text }]); setBusy('chat'); try { const answer = await generate('chat', text); setMessages(m => [...m, { role: 'assistant', text: answer }]); } catch { setMessages(m => [...m, { role: 'assistant', text: reply(text) }]); setNotice('The assistant is temporarily offline; a built-in answer was used.'); } finally { setBusy(null); } };
  const translate = async () => { if (!announcement.trim() || busy) return; setBusy('translate'); try { setTranslated(await generate('translate', announcement)); } catch { setNotice('Translation is temporarily unavailable. Please try again.'); } finally { setBusy(null); } };
  const createComment = async () => { if (busy) return; setBusy('comments'); try { setGeneratedComment(await generate('comment', `Student: ${name}. Overall progress: ${level}. Strength: ${strength}. Next focus: ${focus}.`, { name, level, strength, focus })); } catch { setGeneratedComment(comment); setNotice('The assistant is temporarily offline; a built-in suggestion was used.'); } finally { setBusy(null); } };
  const createAdminDraft = async () => { if (!adminRequest.trim() || busy || role !== 'school-admin') return; setBusy('admin'); setNotice(''); try { setAdminDraft(await generate('admin', adminRequest)); } catch { setNotice('Admin helper is temporarily unavailable. Please try again.'); } finally { setBusy(null); } };

  return <div className="mx-auto max-w-7xl space-y-6 pb-12">
    <header className="relative overflow-hidden rounded-[2rem] bg-slate-950 px-6 py-8 text-white sm:px-9"><div className="absolute -right-20 -top-28 h-72 w-72 rounded-full bg-indigo-500/30 blur-3xl"/><div className="relative flex flex-wrap items-end justify-between gap-5"><div><span className="inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/10 px-3 py-1 text-xs text-indigo-200"><Sparkles className="h-3.5 w-3.5"/> Built for your school</span><h1 className="mt-3 text-4xl font-black">AI Assistant</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-300">Study support for students and practical tools for educators—available in Somali and English.</p></div><div className="flex items-center gap-2 rounded-2xl bg-emerald-400/10 px-4 py-3 text-xs text-emerald-200"><ShieldCheck className="h-4 w-4"/><span><b className="block text-white">School-safe assistance</b>Review suggestions before publishing</span></div></div></header>
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-6">{tools.map(t => <button key={t.id} onClick={() => { setActive(t.id); setNotice(''); }} className={`rounded-2xl border p-4 text-left transition ${active === t.id ? 'border-indigo-500 bg-indigo-50 ring-2 ring-indigo-500/15 dark:bg-indigo-500/10' : 'border-slate-200 bg-white hover:-translate-y-0.5 dark:border-slate-700 dark:bg-slate-900'}`}><t.icon className={`mb-4 h-5 w-5 ${active === t.id ? 'text-indigo-600' : 'text-slate-400'}`}/><p className="text-sm font-bold text-slate-900 dark:text-white">{t.title}</p><p className="mt-1 text-xs text-slate-500">{t.subtitle}</p></button>)}</div>
    {notice && <div role="status" className="rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-800 dark:border-amber-900 dark:bg-amber-950/30 dark:text-amber-200">{notice}</div>}

    {active === 'admin' && <Card className="p-6"><div className="flex items-start gap-3"><div className="rounded-xl bg-indigo-100 p-3 text-indigo-700 dark:bg-indigo-500/10"><Building2 className="h-6 w-6"/></div><div><h2 className="text-xl font-black">Admin Helper</h2><p className="text-sm text-slate-500">Samee ogeysiis, fariin waalid, agenda kulan, warbixin kooban ama qorshe hawleed.</p></div></div>{role !== 'school-admin' ? <div className="mt-6 rounded-2xl bg-amber-50 p-5 text-sm text-amber-800 dark:bg-amber-950/30 dark:text-amber-200"><ShieldCheck className="mb-2 h-5 w-5"/>Qaybtan waxaa isticmaali kara school admin-ka keliya.</div> : <div className="mt-6 grid gap-4 lg:grid-cols-2"><div><label className="mb-2 block text-sm font-bold">Maxaad rabtaa in lagaa caawiyo?</label><textarea maxLength={4000} value={adminRequest} onChange={e => setAdminRequest(e.target.value)} rows={10} className="w-full rounded-2xl border bg-transparent p-4 text-sm dark:border-slate-700"/><button disabled={busy === 'admin' || !adminRequest.trim()} onClick={createAdminDraft} className="mt-3 inline-flex items-center gap-2 rounded-xl bg-indigo-600 px-5 py-3 text-sm font-bold text-white disabled:opacity-50">{busy === 'admin' ? <Loader2 className="h-4 w-4 animate-spin"/> : <Sparkles className="h-4 w-4"/>}{busy === 'admin' ? 'Diyaarinaya…' : 'Diyaari qabyo-qoraalka'}</button></div><div className="rounded-2xl bg-slate-50 p-5 dark:bg-slate-800"><p className="text-xs font-bold uppercase text-slate-400">Natiijada admin-ka</p><div className="mt-4 min-h-40 whitespace-pre-wrap text-sm leading-7">{adminDraft || 'Qabyo-qoraalkaaga wuxuu kasoo muuqan doonaa halkan.'}</div>{adminDraft && <button onClick={() => navigator.clipboard?.writeText(adminDraft)} className="mt-5 inline-flex items-center gap-2 rounded-xl border border-indigo-600 px-4 py-2.5 text-sm font-bold text-indigo-700 dark:text-indigo-300"><ClipboardCopy className="h-4 w-4"/> Copy</button>}</div></div>}<p className="mt-5 text-xs text-amber-600">Hubi magacyada, taariikhaha iyo xogta rasmiga ah ka hor intaadan dirin.</p></Card>}

    {active === 'chat' && <Card className="overflow-hidden"><div className="flex min-h-[520px] flex-col"><div className="border-b border-slate-200 p-5 dark:border-slate-700"><h2 className="flex items-center gap-2 font-bold"><Bot className="h-5 w-5 text-indigo-500"/> Study assistant</h2><p className="text-xs text-slate-500">Ku qor Af-Soomaali ama English.</p></div><div className="flex-1 space-y-4 bg-slate-50/60 p-5 dark:bg-slate-950/30">{messages.map((m, i) => <div key={i} className={`flex ${m.role === 'user' ? 'justify-end' : ''}`}><div className={`max-w-[82%] rounded-2xl px-4 py-3 text-sm leading-6 ${m.role === 'user' ? 'rounded-br-md bg-indigo-600 text-white' : 'rounded-bl-md border bg-white dark:border-slate-700 dark:bg-slate-800'}`}>{m.text}</div></div>)}{busy === 'chat' && <div className="flex items-center gap-2 text-xs text-slate-500"><Loader2 className="h-4 w-4 animate-spin"/> Assistant is thinking…</div>}</div><div className="flex gap-2 border-t border-slate-200 p-4 dark:border-slate-700"><input disabled={busy === 'chat'} value={prompt} onChange={e => setPrompt(e.target.value)} onKeyDown={e => e.key === 'Enter' && send()} placeholder="Ask about maths, science, revision…" maxLength={4000} className="min-w-0 flex-1 rounded-xl border border-slate-200 bg-transparent px-4 py-3 text-sm dark:border-slate-700"/><button disabled={busy === 'chat'} onClick={send} className="rounded-xl bg-indigo-600 px-4 text-white disabled:opacity-50"><Send className="h-4 w-4"/></button></div></div></Card>}
    {active === 'quiz' && <Card className="p-8 text-center"><WandSparkles className="mx-auto h-12 w-12 text-violet-600"/><h2 className="mt-5 text-2xl font-black">Create a ready-to-use quiz</h2><p className="mx-auto mt-2 max-w-2xl text-sm leading-6 text-slate-500">Upload a PDF or build questions manually. Supports Somali, English, Arabic, written answers, automatic marking, scheduling, and class assignment.</p><Link href="/dashboard/online-learning" className="mt-6 inline-flex items-center gap-2 rounded-xl bg-violet-600 px-5 py-3 text-sm font-bold text-white">Open quiz generator <ArrowRight className="h-4 w-4"/></Link></Card>}
    {active === 'comments' && <Card className="p-6"><div className="grid gap-6 lg:grid-cols-2"><div><h2 className="text-xl font-black">Report-card comment</h2><div className="mt-5 grid gap-3"><input value={name} onChange={e => setName(e.target.value)} placeholder="Student name" className="rounded-xl border bg-transparent p-3 dark:border-slate-700"/><select value={level} onChange={e => setLevel(e.target.value)} className="rounded-xl border bg-transparent p-3 dark:border-slate-700"><option value="excellent">Excellent progress</option><option value="good">Good progress</option><option value="developing">Developing</option></select><input value={strength} onChange={e => setStrength(e.target.value)} placeholder="Strength" className="rounded-xl border bg-transparent p-3 dark:border-slate-700"/><input value={focus} onChange={e => setFocus(e.target.value)} placeholder="Next focus" className="rounded-xl border bg-transparent p-3 dark:border-slate-700"/><button disabled={busy === 'comments'} onClick={createComment} className="rounded-xl bg-emerald-600 p-3 text-sm font-bold text-white disabled:opacity-50">{busy === 'comments' ? 'Generating…' : 'Generate comment'}</button></div></div><div className="rounded-2xl bg-slate-50 p-5 dark:bg-slate-800"><p className="text-xs font-bold uppercase text-slate-400">Suggested comment</p><p className="mt-4 text-sm leading-7">{generatedComment || comment}</p><button onClick={() => navigator.clipboard?.writeText(generatedComment || comment)} className="mt-6 flex gap-2 rounded-xl border border-emerald-600 px-4 py-2.5 text-sm font-bold text-emerald-700"><ClipboardCopy className="h-4 w-4"/> Copy suggestion</button></div></div></Card>}
    {active === 'translate' && <Card className="p-6"><h2 className="text-xl font-black">Announcement translator</h2><p className="text-sm text-slate-500">Create a quick Somali or English draft for review.</p><div className="mt-6 grid gap-4 lg:grid-cols-2"><textarea maxLength={4000} value={announcement} onChange={e => setAnnouncement(e.target.value)} rows={8} className="rounded-2xl border bg-transparent p-4 text-sm dark:border-slate-700"/><div className="whitespace-pre-wrap rounded-2xl border border-dashed border-cyan-300 bg-cyan-50/50 p-4 text-sm dark:bg-cyan-950/20">{translated || 'Your translated draft will appear here.'}</div></div><button disabled={busy === 'translate'} onClick={translate} className="mt-4 flex gap-2 rounded-xl bg-cyan-600 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50">{busy === 'translate' ? <Loader2 className="h-4 w-4 animate-spin"/> : <Languages className="h-4 w-4"/>} {busy === 'translate' ? 'Translating…' : 'Translate draft'}</button><p className="mt-3 text-xs text-amber-600">Machine draft: have a fluent speaker review important instructions before sending.</p></Card>}
    {active === 'risk' && <Card className="p-6"><div className="flex justify-between"><div><h2 className="text-xl font-black">Early-risk detection</h2><p className="text-sm text-slate-500">Signals from grades, attendance, and fees—not a final judgment.</p></div>{role === 'school-admin' && <Link href="/dashboard/analytics" className="text-sm font-bold text-indigo-600">Full analytics →</Link>}</div>{role !== 'school-admin' ? <div className="mt-8 rounded-2xl bg-amber-50 p-5 text-sm text-amber-800 dark:bg-amber-950/30 dark:text-amber-200"><ShieldCheck className="mb-2 h-5 w-5"/>Student risk data is restricted to school administrators.</div> : riskLoading ? <Loader2 className="mx-auto my-16 animate-spin"/> : risks.length ? <div className="mt-6 space-y-3">{risks.slice(0,8).map(s => <div key={s.studentId} className="flex flex-wrap items-center justify-between gap-4 rounded-2xl border p-4 dark:border-slate-700"><div className="flex gap-3"><GraduationCap className="text-rose-500"/><div><b>{s.studentName}</b><p className="text-xs text-slate-500">{s.className} · {s.reasons.join(' · ')}</p></div></div><span className="rounded-full bg-rose-500/10 px-3 py-1 text-xs font-black text-rose-600">Risk {s.riskScore}</span></div>)}</div> : <div className="mt-8 flex gap-2 rounded-2xl bg-emerald-50 p-5 text-sm text-emerald-700"><Check/>No students currently match the risk thresholds.</div>}</Card>}
  </div>;
}
