'use client';

import { useEffect, useMemo, useState } from 'react';
import api from '../../utils/api';
import { AlertTriangle, BarChart3, CheckCircle2, ChevronDown, CircleHelp, Clock3, LifeBuoy, Loader2, MessageSquareWarning, Plus, Search, Send, Star, TicketCheck, Users } from 'lucide-react';

type Tab = 'help' | 'tickets' | 'survey' | 'admin';
const faqs = [
    ['How do I reset my password?', 'Open your profile settings and choose Change password. If you cannot sign in, use Forgot password on the login screen.'],
    ['Why is attendance missing?', 'Attendance appears after a teacher submits the register for the selected class, subject, and date. Ask the class teacher if it remains unavailable.'],
    ['Where can I see grades?', 'Open Grades from the dashboard. Students and parents only see results that the school has published.'],
    ['How are fee balances calculated?', 'Your balance is the total invoiced amount minus recorded payments. Contact the school finance office if a recent payment is missing.'],
    ['How will I know when my ticket is answered?', 'Open My tickets here. The status and school administrator response update as soon as the ticket is handled.'],
];
const categories = ['technical', 'account', 'attendance', 'grades', 'fees', 'communication', 'other'];
const statusStyle: Record<string, string> = { open: 'bg-blue-500/10 text-blue-600', in_progress: 'bg-amber-500/10 text-amber-600', resolved: 'bg-emerald-500/10 text-emerald-600', closed: 'bg-slate-500/10 text-slate-500' };

function Card({ children, className = '' }: { children: React.ReactNode; className?: string }) { return <section className={`rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-700/60 dark:bg-slate-800/70 ${className}`}>{children}</section>; }

export default function HelpPage() {
    const [tab, setTab] = useState<Tab>('help'); const [user, setUser] = useState<any>({}); const [tickets, setTickets] = useState<any[]>([]); const [insights, setInsights] = useState<any>(null); const [loading, setLoading] = useState(true); const [notice, setNotice] = useState('');
    const [search, setSearch] = useState(''); const [openFaq, setOpenFaq] = useState<number | null>(0);
    const [form, setForm] = useState({ category: 'technical', subject: '', description: '', priority: 'normal' });
    const [rating, setRating] = useState(0); const [comment, setComment] = useState(''); const [reply, setReply] = useState<Record<string, string>>({});
    const isAdmin = user.role === 'school-admin' || user.role === 'school_admin';

    const load = async (admin = isAdmin) => { setLoading(true); try { const calls: Promise<any>[] = [api.get('/support/tickets')]; if (admin) calls.push(api.get('/support/insights')); const results = await Promise.all(calls); setTickets(results[0].data.data || []); if (results[1]) setInsights(results[1].data.data); } catch (error: any) { setNotice(error?.response?.data?.message || 'Unable to load support tickets.'); setTickets([]); } finally { setLoading(false); } };
    useEffect(() => { const current = JSON.parse(localStorage.getItem('user') || '{}'); setUser(current); load(current.role === 'school-admin' || current.role === 'school_admin'); }, []);
    const submitTicket = async (e: React.FormEvent) => { e.preventDefault(); setNotice(''); try { const response = await api.post('/support/tickets', form); setNotice(response.data.message); setForm({ category: 'technical', subject: '', description: '', priority: 'normal' }); await load(isAdmin); setTab('tickets'); } catch (e: any) { setNotice(e?.response?.data?.message || 'Unable to submit ticket.'); } };
    const submitSurvey = async () => { if (!rating) return setNotice('Choose a rating first.'); try { const response = await api.post('/support/surveys', { rating, comment, context: 'help-center' }); setNotice(response.data.message); setRating(0); setComment(''); } catch (e: any) { setNotice(e?.response?.data?.message || 'Unable to save feedback.'); } };
    const updateTicket = async (ticket: any, status: string) => { try { await api.patch(`/support/tickets/${ticket.id}`, { status, adminReply: reply[ticket.id] ?? ticket.adminReply ?? '' }); setNotice('Ticket updated.'); await load(true); } catch (error: any) { setNotice(error?.response?.data?.message || 'Unable to update ticket.'); } };
    const filteredFaqs = useMemo(() => faqs.filter(([q, a]) => `${q} ${a}`.toLowerCase().includes(search.toLowerCase())), [search]);

    const tabs: { id: Tab; label: string; icon: React.ReactNode }[] = [{ id: 'help', label: 'Help center', icon: <CircleHelp className="h-4 w-4" /> }, { id: 'tickets', label: isAdmin ? 'Support tickets' : 'My tickets', icon: <TicketCheck className="h-4 w-4" /> }, { id: 'survey', label: 'Share feedback', icon: <Star className="h-4 w-4" /> }, ...(isAdmin ? [{ id: 'admin' as Tab, label: 'Recurring complaints', icon: <BarChart3 className="h-4 w-4" /> }] : [])];
    return <div className="space-y-6 pb-10">
        <header className={`${!isAdmin ? 'rounded-3xl bg-[#405bb2] p-6 text-white shadow-lg shadow-indigo-900/10 sm:p-8' : ''}`}><p className={`text-xs font-bold uppercase tracking-[.18em] ${!isAdmin ? 'text-indigo-100' : 'text-indigo-500'}`}>Support</p><h1 className={`mt-1 font-black ${!isAdmin ? 'text-2xl text-white' : 'text-3xl text-slate-900 dark:text-white'}`}>Help & Feedback</h1><p className={`mt-1 text-sm ${!isAdmin ? 'text-indigo-100' : 'text-slate-500'}`}>Find answers, report a problem, or follow your support request.</p></header>
        <nav className="flex gap-2 overflow-x-auto border-b border-slate-200 pb-2 dark:border-slate-700">{tabs.map(item => <button key={item.id} onClick={() => { setTab(item.id); setNotice(''); }} className={`flex shrink-0 items-center gap-2 rounded-xl px-4 py-2 text-sm font-semibold ${tab === item.id ? 'bg-indigo-600 text-white' : 'text-slate-500 hover:bg-slate-100 dark:hover:bg-slate-800'}`}>{item.icon}{item.label}</button>)}</nav>
        {notice && <div className="rounded-xl border border-indigo-500/20 bg-indigo-500/10 p-3 text-sm font-medium text-indigo-600">{notice}</div>}

        {tab === 'help' && <div className="grid gap-6 lg:grid-cols-[1.2fr_.8fr]"><div className="space-y-4"><Card><div className="relative"><Search className="absolute left-3 top-3 h-5 w-5 text-slate-400" /><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search the help center…" className="w-full rounded-xl border border-slate-200 bg-transparent py-2.5 pl-10 pr-3 outline-none focus:ring-2 focus:ring-indigo-500 dark:border-slate-700" /></div></Card><Card><h2 className="mb-4 font-bold text-slate-900 dark:text-white">Frequently asked questions</h2><div className="divide-y divide-slate-100 dark:divide-slate-700">{filteredFaqs.map(([question, answer], index) => <div key={question}><button onClick={() => setOpenFaq(openFaq === index ? null : index)} className="flex w-full items-center justify-between py-4 text-left text-sm font-semibold"><span>{question}</span><ChevronDown className={`h-4 w-4 transition ${openFaq === index ? 'rotate-180' : ''}`} /></button>{openFaq === index && <p className="pb-4 text-sm leading-6 text-slate-500">{answer}</p>}</div>)}</div></Card></div>
        <Card><div className="mb-5 flex items-center gap-3"><div className="rounded-xl bg-rose-500/10 p-2 text-rose-500"><MessageSquareWarning className="h-5 w-5" /></div><div><h2 className="font-bold text-slate-900 dark:text-white">Report a problem</h2><p className="text-xs text-slate-500">Create a trackable support ticket.</p></div></div><form onSubmit={submitTicket} className="space-y-3"><div className="grid grid-cols-2 gap-3"><select value={form.category} onChange={e => setForm({ ...form, category: e.target.value })} className="rounded-xl border border-slate-200 bg-transparent p-2.5 text-sm dark:border-slate-700">{categories.map(c => <option key={c} value={c}>{c[0].toUpperCase() + c.slice(1)}</option>)}</select><select value={form.priority} onChange={e => setForm({ ...form, priority: e.target.value })} className="rounded-xl border border-slate-200 bg-transparent p-2.5 text-sm dark:border-slate-700">{['low', 'normal', 'high', 'urgent'].map(p => <option key={p}>{p}</option>)}</select></div><input required maxLength={140} value={form.subject} onChange={e => setForm({ ...form, subject: e.target.value })} placeholder="Short problem summary" className="w-full rounded-xl border border-slate-200 bg-transparent p-2.5 text-sm dark:border-slate-700" /><textarea required rows={6} maxLength={5000} value={form.description} onChange={e => setForm({ ...form, description: e.target.value })} placeholder="What happened? Include the page and steps that caused it." className="w-full resize-none rounded-xl border border-slate-200 bg-transparent p-2.5 text-sm dark:border-slate-700" /><button className="flex w-full items-center justify-center gap-2 rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-bold text-white"><Send className="h-4 w-4" /> Submit ticket</button></form></Card></div>}

        {tab === 'tickets' && <div className="space-y-4">{loading ? <Loader2 className="mx-auto mt-16 h-8 w-8 animate-spin text-indigo-500" /> : !tickets.length ? <Card className="py-14 text-center"><LifeBuoy className="mx-auto mb-3 h-8 w-8 text-slate-400" /><p className="font-semibold">No support tickets yet.</p></Card> : tickets.map(ticket => <Card key={ticket.id}><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="mb-2 flex flex-wrap gap-2"><span className={`rounded-full px-2 py-1 text-xs font-bold ${statusStyle[ticket.status]}`}>{ticket.status.replace('_', ' ')}</span><span className="rounded-full bg-slate-100 px-2 py-1 text-xs dark:bg-slate-700">{ticket.category}</span><span className="text-xs font-semibold text-rose-500">{ticket.priority}</span></div><h3 className="font-bold text-slate-900 dark:text-white">{ticket.subject}</h3>{isAdmin && <p className="text-xs text-slate-500">From {ticket.requester.firstName} {ticket.requester.lastName} · {ticket.requester.role}</p>}</div><span className="flex items-center gap-1 text-xs text-slate-400"><Clock3 className="h-3.5 w-3.5" />{new Date(ticket.createdAt).toLocaleDateString()}</span></div><p className="mt-4 whitespace-pre-wrap text-sm leading-6 text-slate-600 dark:text-slate-300">{ticket.description}</p>{ticket.adminReply && <div className="mt-4 rounded-xl bg-emerald-500/10 p-3"><p className="mb-1 text-xs font-bold text-emerald-600">Administrator response</p><p className="text-sm">{ticket.adminReply}</p></div>}{isAdmin && <div className="mt-4 space-y-2 border-t border-slate-100 pt-4 dark:border-slate-700"><textarea rows={2} value={reply[ticket.id] ?? ticket.adminReply ?? ''} onChange={e => setReply({ ...reply, [ticket.id]: e.target.value })} placeholder="Write a response…" className="w-full rounded-xl border border-slate-200 bg-transparent p-2.5 text-sm dark:border-slate-700" /><div className="flex flex-wrap gap-2">{['in_progress', 'resolved', 'closed'].map(status => <button key={status} onClick={() => updateTicket(ticket, status)} className="rounded-lg border border-slate-200 px-3 py-1.5 text-xs font-semibold dark:border-slate-700">Mark {status.replace('_', ' ')}</button>)}</div></div>}</Card>)}</div>}

        {tab === 'survey' && <Card className="mx-auto max-w-2xl text-center"><Star className="mx-auto mb-3 h-8 w-8 text-amber-500" /><h2 className="text-xl font-black text-slate-900 dark:text-white">How satisfied are you with SchoolOS?</h2><p className="mt-1 text-sm text-slate-500">Your feedback helps the school improve its digital services.</p><div className="my-6 flex justify-center gap-2">{[1, 2, 3, 4, 5].map(value => <button key={value} onClick={() => setRating(value)} aria-label={`${value} stars`}><Star className={`h-9 w-9 ${value <= rating ? 'fill-amber-400 text-amber-400' : 'text-slate-300'}`} /></button>)}</div><textarea rows={4} value={comment} onChange={e => setComment(e.target.value)} maxLength={2000} placeholder="Tell us what is working well or what we should improve…" className="w-full resize-none rounded-xl border border-slate-200 bg-transparent p-3 text-left text-sm dark:border-slate-700" /><button onClick={submitSurvey} className="mt-4 rounded-xl bg-indigo-600 px-6 py-2.5 text-sm font-bold text-white">Send feedback</button></Card>}

        {tab === 'admin' && isAdmin && insights && <div className="space-y-5"><div className="grid gap-4 sm:grid-cols-3">{[['Tickets · 90 days', insights.totalTickets, <TicketCheck key="t" />], ['Currently open', insights.openTickets, <AlertTriangle key="o" />], ['Satisfaction', `${insights.satisfaction.average}/5`, <Star key="s" />]].map(([label, value, icon]: any) => <Card key={label}><div className="mb-2 text-indigo-500">{icon}</div><p className="text-2xl font-black">{value}</p><p className="text-xs text-slate-500">{label}</p></Card>)}</div><Card><h2 className="mb-1 flex items-center gap-2 font-bold"><Users className="h-5 w-5 text-rose-500" /> Recurring complaints</h2><p className="mb-5 text-xs text-slate-500">Categories reported at least twice in the last 90 days.</p>{!insights.recurringComplaints.length ? <div className="flex items-center gap-2 text-sm text-emerald-600"><CheckCircle2 className="h-5 w-5" /> No recurring complaint patterns detected.</div> : <div className="space-y-3">{insights.recurringComplaints.map((item: any) => <div key={item.category} className="rounded-xl border border-slate-200 p-4 dark:border-slate-700"><div className="flex justify-between"><p className="font-bold capitalize">{item.category}</p><span className="rounded-full bg-rose-500/10 px-2 py-1 text-xs font-bold text-rose-500">{item.count} reports · {item.open} open</span></div><p className="mt-2 text-xs text-slate-500">Recent: {item.latestSubjects.join(' · ')}</p></div>)}</div>}</Card></div>}
    </div>;
}
