const router = require('express').Router();
const controller = require('../controllers/onlineLearning.controller');
const { protect } = require('../middlewares/auth.middleware');
const upload = require('../middlewares/upload.middleware');
const { verifyUploadedFile } = require('../middlewares/upload.middleware');
router.use(protect);
router.route('/courses').get(controller.getCourses).post(controller.createCourse);
router.post('/courses/:courseId/lessons', controller.addLesson);
router.put('/lessons/:lessonId/progress', controller.saveProgress);
router.post('/quizzes', controller.createClassQuiz);
router.post('/courses/:courseId/quizzes', controller.createQuiz);
router.post('/courses/:courseId/quizzes/from-pdf', upload.single('pdf'), verifyUploadedFile, controller.createQuizFromPdf);
router.post('/quizzes/from-pdf', upload.single('pdf'), verifyUploadedFile, controller.createQuizFromPdf);
router.get('/quizzes/:quizId/results', controller.getQuizResults);
router.get('/quizzes/:quizId', controller.getQuiz);
router.post('/quizzes/:quizId/submit', controller.submitQuiz);
router.put('/quizzes/:quizId', controller.updateQuiz);
router.delete('/quizzes/:quizId', controller.deleteQuiz);
module.exports = router;
